Adding WorkerTypes filtering feature (#149)
* [WIP] Adding WorkerTypes filter feature

Trying to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1275874
I am trying to figure out the way to filter the list of WorkerType summaries. I think the filtering should happen in load() function... but cannot wrap my head around it :) Maybe I am missing something, or going in completely different direction? Any feedback would be much appreciated! Thank you!

* Update workertypetable.js

I corrected the load() function. However, nothing is being loaded, because I still get "Uncaught TypeError: this.awsProvisioner.listWorkerTypeSummaries(...).filter is not a function". Not sure what is wrong... *sigh*

* Update workertypetable.js

Seems to be working!

* Update workertypetable.js

Changed arguments names back

* Update workertypetable.js

Corrected lint errors

* Update workertypetable.js

Removed unnecessary semicolon

* Update workertypetable.js

Corected lint error

* Update workertypetable.js

Fixed more lint errors

* Update workertypetable.js

Preliminary. Some of the changes requested by eliperelman

* Update workertypetable.js

More requested changes

* Update workertypetable.js

Support for full-text filtering instead of just the beginning of the text

* Update workertypetable.js

Also changed state property name

* Update workertypetable.js

Moved the search bar to be right above the table

* Update workertypetable.js

Moved the input element under the table heading