Update workertypetable.js
I corrected the load() function. However, nothing is being loaded, because I still get "Uncaught TypeError: this.awsProvisioner.listWorkerTypeSummaries(...).filter is not a function". Not sure what is wrong... *sigh*